internal object LibsVersion {
    const val buildGradle = "4.2.0-alpha04"
    const val kotlin = "1.4.32"
    const val coreKtx = "1.3.2"
    const val appCompat = "1.2.0"
    const val material = "1.3.0"
    const val constraintLayout = "2.0.4"
    const val recyclerView = "1.1.0"
    const val swipeRefreshLayout = "1.1.0"
    const val navigation = "2.3.5"
    const val fragmentKtx = "1.3.3"
    const val paging = "3.0.0-rc01"
    const val lifecycleKtx = "2.3.1"
    const val moshi = "1.9.3"
    const val moshiConverter = "2.9.0"
    const val retrofit = "2.9.0"
    const val loggingInterceptor = "4.9.0"
    const val koin = "2.2.2"
}

object Libs {
    const val buildGradle = "com.android.tools.build:gradle:${LibsVersion.buildGradle}"
    const val kotlinPlugin = "org.jetbrains.kotlin:kotlin-gradle-plugin:${LibsVersion.kotlin}"
    const val kotlinStdlib = "org.jetbrains.kotlin:kotlin-stdlib:${LibsVersion.kotlin}"
    const val coreKtx = "androidx.core:core-ktx:${LibsVersion.coreKtx}"
    const val appCompat = "androidx.appcompat:appcompat:${LibsVersion.appCompat}"
    const val material = "com.google.android.material:material:${LibsVersion.material}"
    const val constraintLayout = "androidx.constraintlayout:constraintlayout:${LibsVersion.constraintLayout}"
    const val recyclerView = "androidx.recyclerview:recyclerview:${LibsVersion.recyclerView}"
    const val swipeRefreshLayout = "androidx.swiperefreshlayout:swiperefreshlayout:${LibsVersion.swipeRefreshLayout}"
    const val fragmentKtx = "androidx.fragment:fragment-ktx:${LibsVersion.fragmentKtx}"
    const val navigationFragmentKtx = "androidx.navigation:navigation-fragment-ktx:${LibsVersion.navigation}"
    const val navigationUIKtx = "androidx.navigation:navigation-ui-ktx:${LibsVersion.navigation}"
    const val paging = "androidx.paging:paging-runtime-ktx:${LibsVersion.paging}"
    const val lifecycleLiveData = "androidx.lifecycle:lifecycle-livedata-ktx:${LibsVersion.lifecycleKtx}"
    const val lifecycleViewModel = "androidx.lifecycle:lifecycle-viewmodel-ktx:${LibsVersion.lifecycleKtx}"
    const val moshi = "com.squareup.moshi:moshi-kotlin:${LibsVersion.moshi}"
    const val moshiConverter = "com.squareup.retrofit2:converter-moshi:${LibsVersion.moshiConverter}"
    const val retrofit = "com.squareup.retrofit2:retrofit:${LibsVersion.retrofit}"
    const val loggingInterceptor = "com.squareup.okhttp3:logging-interceptor:${LibsVersion.loggingInterceptor}"

    const val koinScope = "org.koin:koin-androidx-scope:${LibsVersion.koin}"
    const val koinViewModel = "org.koin:koin-androidx-viewmodel:${LibsVersion.koin}"
    const val koinFragment = "org.koin:koin-androidx-fragment:${LibsVersion.koin}"
    const val koinExt = "org.koin:koin-androidx-ext:${LibsVersion.koin}"
}